// src/constants.ts
import { ToolType, ToolDef } from './types';
import {
  FileText,
  FileCode,
  Code,
  Braces,
  Scan,
  Brain,
  BookOpen,
  MessageCircle,
  Layers,
  Scissors,
  LayoutPanelTop,
  MessageSquare
} from 'lucide-react';

export const TOOLS: ToolDef[] = [
  {
    id: ToolType.TO_TEXT,
    title: "PDF to Text",
    description: "Extract clean text from any PDF.",
    icon: FileText,
    category: "AI Conversion",
    color: "bg-rose-600",
  },
  {
    id: ToolType.TO_MARKDOWN,
    title: "PDF to Markdown",
    description: "Convert PDFs into Markdown.",
    icon: FileCode,
    category: "AI Conversion",
    color: "bg-rose-600",
  },
  {
    id: ToolType.TO_HTML,
    title: "PDF to HTML",
    description: "Convert PDFs into clean HTML.",
    icon: Code,
    category: "AI Conversion",
    color: "bg-rose-600",
  },
  {
    id: ToolType.TO_JSON,
    title: "PDF to JSON",
    description: "Extract structured data.",
    icon: Braces,
    category: "AI Conversion",
    color: "bg-rose-600",
  },
  {
    id: ToolType.OCR_PDF,
    title: "OCR PDF",
    description: "Extract text from scanned PDFs.",
    icon: Scan,
    category: "OCR",
    color: "bg-amber-600",
  },
  {
    id: ToolType.SUMMARIZE,
    title: "Summarize PDF",
    description: "Generate a smart summary.",
    icon: BookOpen,
    category: "AI Understanding",
    color: "bg-indigo-600",
  },
  {
    id: ToolType.EXPLAIN,
    title: "Explain PDF",
    description: "Simplify complex documents.",
    icon: Brain,
    category: "AI Understanding",
    color: "bg-indigo-600",
  },
  {
    id: ToolType.CHAT_PDF,
    title: "Chat with PDF",
    description: "Ask questions about your document.",
    icon: MessageSquare,
    category: "AI Understanding",
    color: "bg-indigo-600",
  },
  {
    id: ToolType.DOCUMENT_ANALYSIS,
    title: "Analyze PDF",
    description: "AI-powered document insights.",
    icon: LayoutPanelTop,
    category: "AI Understanding",
    color: "bg-indigo-600",
  },
  {
    id: ToolType.MERGE_PDF,
    title: "Merge PDFs",
    description: "Combine multiple PDFs.",
    icon: Layers,
    category: "PDF Tools",
    color: "bg-emerald-600",
  },
  {
    id: ToolType.SPLIT_PDF,
    title: "Split PDF",
    description: "Extract selected pages.",
    icon: Scissors,
    category: "PDF Tools",
    color: "bg-emerald-600",
  },
];
